parameters:
#    meeting_app_core.example.class: MeetingApp\CoreBundle\Example

services:
#    meeting_app_core.example:
#        class: %meeting_app_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
